# Generated by Django 4.1.7 on 2023-03-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('address', models.TextField()),
                ('mobile', models.IntegerField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
